apiVersion: v1
kind: Service
metadata:
  name: ford-price-service
spec:
  type: NodePort
  selector:
    app: ford-price
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080