apiVersion: v1
kind: Service
metadata:
  name: uber-price-service
  labels:
    app: uber-price
spec:
  type: NodePort
  selector:
    app: uber-price
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080
